<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xfhoj8\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xfhoj8/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5xfhoj8.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5xfhoj8\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5xfhoj8\appProdProjectContainer([
    'container.build_hash' => '5xfhoj8',
    'container.build_id' => '00fd8acd',
    'container.build_time' => 1622469815,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xfhoj8');
